services:
  # Frontend React Application
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - challenge-network
    depends_on:
      - api-gateway

  # API Gateway
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - TASKS_SERVICE_URL=http://tasks-service:3002
    depends_on:
      auth-db:
        condition: service_started
      tasks-db:
        condition: service_started
      rabbitmq:
        condition: service_started
      auth-service:
        condition: service_started
      tasks-service:
        condition: service_started
    networks:
      - challenge-network

  # Auth Service
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      - PORT=3001
      - DB_HOST=auth-db
      - DB_NAME=auth_db
    depends_on:
      auth-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-network

  # Tasks Service
  tasks-service:
    container_name: tasks-service
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file: .env
    environment:
      - PORT=3002
      - DB_HOST=tasks-db
      - DB_NAME=tasks_db
    depends_on:
      tasks-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-network

  # Notifications Service
  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file: .env
    environment:
      - PORT=3003
    depends_on:
      rabbitmq:
        condition: service_started
    networks:
      - challenge-network

  # Auth Database
  auth-db:
    image: postgres:17.5-alpine3.21
    container_name: auth-db
    ports:
      - "5432:5432"
    networks:
      - challenge-network
    restart: always
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: auth_db

  # Tasks Database
  tasks-db:
    image: postgres:17.5-alpine3.21
    container_name: tasks-db
    ports:
      - "5431:5432"
    networks:
      - challenge-network
    restart: always
    volumes:
      - postgres_tasks_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: tasks_db

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - challenge-network
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_auth_data:
    driver: local
  postgres_tasks_data:
    driver: local
  rabbitmq_data:
    driver: local
  node_modules_root:
    driver: local
  api_gateway_node_modules:
    driver: local
  auth_service_node_modules:
    driver: local
  tasks_service_node_modules:
    driver: local
  notifications_service_node_modules:
    driver: local
  web_node_modules:
    driver: local

networks:
  challenge-network:
    driver: bridge
